on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  run_pr_checks:
    uses: ./.github/workflows/pr_checks.yml

  create_changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.github_release.outputs.changelog }}
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          commitMode: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_issue:
    needs: [run_pr_checks, create_changelog]
    if: ${{ always() }}
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show link to tests
        run: echo ${{ needs.run_pr_checks.outputs.url }}

      - name: Create Issue
        uses: JasonEtco/create-an-issue@v2
        env:
          version: ${{ github.ref }}
          tests_url: ${{ needs.run_pr_checks.outputs.url }}
          changelog: ${{ needs.create_changelog.outputs.changelog }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          update_existing: true

  create_release:
    needs: [run_pr_checks, create_changelog]
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release version ${{ github.ref }}
          body: |
            ## Changelog:
            ${{ needs.create_changelog.outputs.changelog }}
            ## Tests result:
            ${{ env.tests_report }}

          draft: false
          prerelease: false
